import { useCallback, useEffect, useMemo, useState } from 'react'
import './student.css'

const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:4000/api'
const sections = [
  ['dashboard', 'Dashboard', '⌂'], ['profile', 'Profile', '◎'], ['skills', 'Skills', '◆'],
  ['passport', 'Skill Passport', '✦'], ['gaps', 'Skill Gaps', '↗'], ['career', 'Career Path', '◇'],
  ['learning', 'Learning', '◷'], ['assessments', 'Assessments', '✓'],
  ['opportunities', 'Opportunities', '↗'], ['applications', 'Applications', '▣'],
  ['internships', 'Internships', '◌'], ['portfolio', 'Portfolio', '▤'],
  ['certifications', 'Certifications', '◇'], ['notifications', 'Notifications', '♧'], ['settings', 'Settings', '⚙'],
]

async function request(path, token, options = {}) {
  const response = await fetch(`${API_URL}${path}`, { ...options, headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}`, ...(options.headers || {}) } })
  const result = await response.json()
  if (!response.ok || !result.success) throw new Error(result.error?.message || 'Unable to load student data')
  return result.data
}

function label(value) { return String(value || '').replaceAll('_', ' ').toLowerCase().replace(/\b\w/g, (letter) => letter.toUpperCase()) }

export default function StudentDashboard({ token, profile, onSignOut }) {
  const [section, setSection] = useState('dashboard')
  const [dashboard, setDashboard] = useState(null)
  const [studentProfile, setStudentProfile] = useState(null)
  const [skillsData, setSkillsData] = useState(null)
  const [gaps, setGaps] = useState([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const [notice, setNotice] = useState('')

  const load = useCallback(async () => {
    setLoading(true); setError('')
    try {
      const [dashboardResult, profileResult, skillsResult, gapsResult] = await Promise.all([
        request('/students/me/dashboard', token), request('/students/me/profile', token), request('/students/me/skills', token), request('/students/me/skill-gaps', token),
      ])
      setDashboard(dashboardResult); setStudentProfile(profileResult); setSkillsData(skillsResult); setGaps(gapsResult.gaps || [])
    } catch (loadError) { setError(loadError.message) } finally { setLoading(false) }
  }, [token])

  useEffect(() => { load() }, [load])

  async function addSkill(event) {
    event.preventDefault(); const form = new FormData(event.currentTarget)
    try { await request('/students/me/skills', token, { method: 'POST', body: JSON.stringify({ name: form.get('name'), level: form.get('level') }) }); event.currentTarget.reset(); setNotice('Skill added to your passport'); await load() } catch (saveError) { setError(saveError.message) }
  }

  async function saveProfile(event) {
    event.preventDefault(); const form = new FormData(event.currentTarget)
    try { await request('/students/me/profile', token, { method: 'PATCH', body: JSON.stringify(Object.fromEntries(form.entries())) }); setNotice('Profile updated'); await load() } catch (saveError) { setError(saveError.message) }
  }

  const activeTitle = sections.find(([key]) => key === section)?.[1] || 'Dashboard'
  const metrics = dashboard?.metrics || {}
  const firstName = studentProfile?.firstName || profile?.user?.fullName?.split(' ')[0] || 'Student'

  if (loading && !dashboard) return <main className="student-state"><div className="student-state-card"><span className="student-spinner" /><p className="student-kicker">STUDENT WORKSPACE</p><h1>Building your career view</h1><p>Loading your live skills, profile, and opportunities.</p></div></main>
  if (error && !dashboard) return <main className="student-state"><div className="student-state-card"><p className="student-kicker">STUDENT WORKSPACE</p><h1>Workspace unavailable</h1><p>{error}</p><button className="student-button" onClick={load}>Try again</button><button className="student-link" onClick={onSignOut}>Sign out</button></div></main>

  return <div className="student-shell">
    <aside className="student-sidebar">
      <div className="student-brand"><span className="student-mark">E</span><span>EduNexus</span></div>
      <div className="student-profile-mini"><span>{firstName.slice(0, 2).toUpperCase()}</span><div><strong>{studentProfile?.first_name} {studentProfile?.last_name}</strong><small>{studentProfile?.course || 'Student workspace'}</small></div></div>
      <nav aria-label="Student navigation"><p className="student-nav-label">MY CAREER SPACE</p>{sections.map(([key, title, icon]) => <button key={key} className={`student-nav-item ${section === key ? 'active' : ''}`} onClick={() => setSection(key)}><span>{icon}</span>{title}</button>)}</nav>
      <div className="student-sidebar-foot"><button className="student-nav-item" onClick={onSignOut}><span>↪</span>Sign out</button><small>Build evidence. Grow with intent.</small></div>
    </aside>
    <main className="student-main">
      <header className="student-topbar"><button className="student-mobile-menu" aria-label="Open navigation">☰</button><div className="student-breadcrumb">Student <span>/</span> {activeTitle}</div><div className="student-top-actions"><button aria-label="Search">⌕</button><button aria-label="Notifications">♧</button><button className="student-user" onClick={onSignOut}><span>{firstName.slice(0, 2).toUpperCase()}</span><b>{firstName}</b>⌄</button></div></header>
      <div className="student-page">
        {notice && <div className="student-notice" role="status">✓ {notice}<button onClick={() => setNotice('')} aria-label="Dismiss">×</button></div>}
        {error && <div className="student-error" role="alert">{error}<button onClick={() => setError('')}>Dismiss</button></div>}
        {section === 'dashboard' && <DashboardView firstName={firstName} dashboard={dashboard} metrics={metrics} onSelect={setSection} />}
        {section === 'profile' && <ProfileView profile={studentProfile} onSubmit={saveProfile} />}
        {section === 'skills' && <SkillsView data={skillsData} onSubmit={addSkill} />}
        {section === 'passport' && <PassportView skills={skillsData?.skills || []} />}
        {section === 'gaps' && <GapsView gaps={gaps} />}
        {section === 'career' && <CareerView gaps={gaps} />}
        {section === 'learning' && <LearningView gaps={gaps} />}
        {section === 'assessments' && <EmptyView title="Assessments" copy="Assessment attempts will appear here as your skill history grows." action="Explore skill gaps" onAction={() => setSection('gaps')} />}
        {['opportunities', 'applications', 'internships', 'portfolio', 'certifications', 'notifications', 'settings'].includes(section) && <CareerExecutionView section={section} token={token} onSelect={setSection} onNotice={setNotice} onError={setError} />}
      </div>
    </main>
  </div>
}

function Header({ kicker, title, copy, action, onAction }) { return <section className="student-heading"><div><p className="student-kicker">{kicker}</p><h1>{title}</h1><p>{copy}</p></div>{action && <button className="student-button" onClick={onAction}>{action} <span>→</span></button>}</section> }

function DashboardView({ firstName, dashboard, metrics, onSelect }) { return <><Header kicker="YOUR CAREER WORKSPACE" title={<>Good morning, {firstName} <i>✦</i></>} copy="A clear view of where you are, what matters next, and how to move forward." action="Complete profile" onAction={() => onSelect('profile')} /><section className="student-metric-grid"><Metric label="Profile completion" value={`${metrics.profileCompletion || 0}%`} note="Keep your story current" tone="violet" /><Metric label="Skill readiness" value={`${metrics.readiness || 0}%`} note={`${metrics.assessedSkills || 0} assessed skills`} tone="teal" /><Metric label="Evidence collected" value={metrics.evidence || 0} note={`${metrics.projects || 0} projects documented`} tone="amber" /><Metric label="Active skill gaps" value={dashboard?.gaps?.length || 0} note="Prioritized for your goal" tone="coral" /></section><div className="student-grid-two"><article className="student-panel readiness-panel"><PanelTitle kicker="SKILL PASSPORT" title="Your progress, with proof" action="Open passport" onAction={() => onSelect('passport')} /><div className="readiness-row"><div className="readiness-ring" style={{ '--progress': `${metrics.readiness || 0}%` }}><strong>{metrics.readiness || 0}<small>%</small></strong></div><div><h3>{metrics.readiness >= 70 ? 'You are gaining momentum' : 'Your next proof point is clear'}</h3><p>{metrics.evidence ? `${metrics.evidence} pieces of evidence support your skills.` : 'Add a project or certification to make your skills more credible.'}</p><button className="student-link" onClick={() => onSelect('skills')}>Strengthen my passport →</button></div></div></article><article className="student-panel action-panel"><PanelTitle kicker="NEXT BEST MOVES" title="Small steps, visible progress" /><div className="action-list">{(dashboard?.nextActions?.length ? dashboard.nextActions : ['Complete your profile', 'Add evidence to a skill', 'Review your skill gaps']).map((action, index) => <button key={action} onClick={() => onSelect(index === 0 ? 'profile' : index === 1 ? 'skills' : 'gaps')}><span>0{index + 1}</span><b>{action}</b><i>↗</i></button>)}</div></article></div><article className="student-panel gap-panel"><PanelTitle kicker="DEMAND SIGNALS" title="Skills employers are asking for" action="View all gaps" onAction={() => onSelect('gaps')} /><div className="gap-list">{(dashboard?.gaps || []).map((gap) => <div className="gap-row" key={`${gap.skill}-${gap.role}`}><div><strong>{gap.skill}</strong><small>{gap.role} · {gap.currentLevel} → {gap.requiredLevel}</small></div><span className={`student-badge ${gap.priority === 'MANDATORY' ? 'priority' : ''}`}>{label(gap.priority)}</span></div>)}{!dashboard?.gaps?.length && <EmptyText copy="Your current skills align with the available demand signals." />}</div></article></> }

function PanelTitle({ kicker, title, action, onAction }) { return <div className="student-panel-title"><div><p className="student-kicker">{kicker}</p><h2>{title}</h2></div>{action && <button className="student-link" onClick={onAction}>{action} →</button>}</div> }
function Metric({ label: metricLabel, value, note, tone }) { return <article className={`student-metric ${tone}`}><span>{metricLabel}</span><strong>{value}</strong><small>{note}</small></article> }

function ProfileView({ profile, onSubmit }) { return <><Header kicker="YOUR FOUNDATION" title="Profile" copy="Keep the details behind your ambition clear and current." /><form className="student-panel profile-form" onSubmit={onSubmit}><PanelTitle kicker="PERSONAL INFORMATION" title="Tell your story" /><div className="student-form-grid"><Field name="first_name" label="First name" value={profile?.first_name} /><Field name="last_name" label="Last name" value={profile?.last_name} /><Field name="institution_name" label="Institution" value={profile?.institution_name} /><Field name="course" label="Course" value={profile?.course} /><Field name="graduation_year" label="Graduation year" value={profile?.graduation_year} type="number" /><Field name="location" label="Location" value={profile?.location} /><label className="wide-field">Bio<textarea name="bio" defaultValue={profile?.bio || ''} rows="4" placeholder="What are you learning, building, or working toward?" /></label><Field name="portfolio_url" label="Portfolio URL" value={profile?.portfolio_url} /></div><button className="student-button">Save profile <span>→</span></button></form></> }
function Field({ name, label: fieldLabel, value, type = 'text' }) { return <label>{fieldLabel}<input name={name} type={type} defaultValue={value || ''} /></label> }
function SkillsView({ data, onSubmit }) { const [search, setSearch] = useState(''); const available = useMemo(() => (data?.available || []).filter((skill) => skill.name.toLowerCase().includes(search.toLowerCase())).slice(0, 8), [data, search]); return <><Header kicker="SKILL INTELLIGENCE" title="Skills" copy="Build a skill set you can explain, evidence, and grow." /><div className="student-grid-two"><form className="student-panel add-skill-form" onSubmit={onSubmit}><PanelTitle kicker="ADD A SKILL" title="What are you practicing?" /><input name="name" list="skill-options" placeholder="Search the shared taxonomy" required onChange={(event) => setSearch(event.target.value)} /><datalist id="skill-options">{available.map((skill) => <option key={skill.id} value={skill.name} />)}</datalist><select name="level" defaultValue="BASIC"><option value="BASIC">Basic</option><option value="INTERMEDIATE">Intermediate</option><option value="ADVANCED">Advanced</option><option value="EXPERT">Expert</option></select><button className="student-button">Add to passport <span>＋</span></button></form><article className="student-panel"><PanelTitle kicker="YOUR INVENTORY" title={`${data?.skills?.length || 0} skills in focus`} /><div className="skill-card-list">{(data?.skills || []).map((skill) => <div className="skill-card" key={skill.id}><span className="skill-orb">{skill.name.slice(0, 1)}</span><div><strong>{skill.name}</strong><small>{label(skill.category)} · {label(skill.verified_level || skill.self_level)}</small></div><span className="student-badge">{skill.evidence_count ? `${skill.evidence_count} proof` : 'Needs proof'}</span></div>)}{!data?.skills?.length && <EmptyText copy="Add your first skill to start your passport." />}</div></article></div></> }
function PassportView({ skills }) { return <><Header kicker="PROFESSIONAL IDENTITY" title="Skill Passport" copy="A living record of what you know and how you can prove it." /><article className="passport-hero"><div><p className="student-kicker">EDUNEXUS SKILL PASSPORT</p><h2>Evidence-backed skills<br />open better doors.</h2><p>Self-declared skills become more trusted as you add assessments, projects, and verified evidence.</p></div><div className="passport-seal">E<br /><small>PASSPORT</small></div></article><article className="student-panel passport-list"><PanelTitle kicker="CREDENTIALS" title="Your skills at a glance" />{skills.map((skill) => <div className="passport-row" key={skill.id}><div className="passport-skill"><span className="skill-orb">{skill.name.slice(0, 1)}</span><div><strong>{skill.name}</strong><small>{label(skill.category)}</small></div></div><div><span className="trust-label">{skill.verified_level ? 'Assessed' : 'Self declared'}</span><small>{label(skill.verified_level || skill.self_level)} · {skill.evidence_count} evidence</small></div><div className="passport-bar"><span style={{ width: `${(skill.verified_level ? 75 : 35) + Math.min(skill.evidence_count * 10, 25)}%` }} /></div></div>)}{!skills.length && <EmptyText copy="Your passport will appear here once you add skills." />}</article></> }
function GapsView({ gaps }) { return <><Header kicker="SKILL INTELLIGENCE" title="Skill gaps" copy="Turn career requirements into a focused, actionable learning queue." /><div className="student-gap-hero"><div><p className="student-kicker">TARGET SIGNALS</p><h2>Your next advantage is specific.</h2><p>These gaps are calculated by comparing your verified skills with live published role requirements.</p></div><strong>{gaps.length}<small>priority gaps</small></strong></div><div className="gap-detail-list">{gaps.map((gap) => <article className="student-panel gap-detail" key={`${gap.skill}-${gap.role}`}><div className="gap-detail-head"><div><span className="student-badge priority">{label(gap.priority)}</span><h2>{gap.skill}</h2><p>{gap.role}</p></div><strong>{gap.currentLevel}<span>current</span></strong><b>→</b><strong>{gap.requiredLevel}<span>required</span></strong></div><div className="gap-explanation"><span>Gap of {gap.gap} level{gap.gap === 1 ? '' : 's'}</span><p>{gap.recommendation}</p><button className="student-link">Create learning plan →</button></div></article>)}{!gaps.length && <EmptyView title="No priority gaps" copy="Your current profile aligns with the available role requirements." />}</div></> }
function CareerView({ gaps }) { return <><Header kicker="CAREER DIRECTION" title="Career path" copy="See the sequence between where you are and where you want to go." /><article className="student-panel career-path"><PanelTitle kicker="YOUR JOURNEY" title="From curious to career ready" /><div className="journey">{['Profile', 'Skill gap', 'Learning', 'Assessment', 'Project', 'Career ready'].map((step, index) => <div className={index === 1 && gaps.length ? 'journey-step current' : 'journey-step'} key={step}><span>{String(index + 1).padStart(2, '0')}</span><strong>{step}</strong>{index < 5 && <i>↓</i>}</div>)}</div></article><article className="student-panel career-note"><p className="student-kicker">RECOMMENDED FOCUS</p><h2>{gaps[0] ? `Build confidence in ${gaps[0].skill}` : 'Your path is taking shape'}</h2><p>{gaps[0]?.recommendation || 'Keep adding evidence and assessments to make your direction more visible to future collaborators.'}</p></article></> }
function LearningView({ gaps }) { return <><Header kicker="LEARNING WORKSPACE" title="Learning" copy="Learning recommendations shaped by your current gaps and goals." /><div className="student-grid-two"><article className="student-panel learning-feature"><p className="student-kicker">NEXT RECOMMENDATION</p><h2>{gaps[0] ? `${gaps[0].skill} foundations` : 'Your learning queue is ready'}</h2><p>{gaps[0] ? gaps[0].recommendation : 'Review your skill passport to unlock focused recommendations.'}</p><button className="student-button">Start a plan <span>→</span></button></article><article className="student-panel"><PanelTitle kicker="MY PLANS" title="Progress you can see" /><EmptyText copy="Learning plans will appear here when you choose a skill gap to work on." /></article></div></> }
function EmptyView({ title, copy, action, onAction }) { return <div className="student-empty"><span>✦</span><h2>{title}</h2><p>{copy}</p>{action && <button className="student-button" onClick={onAction}>{action} →</button>}</div> }
function EmptyText({ copy }) { return <p className="student-empty-text">{copy}</p> }

function CareerExecutionView({ section, token, onSelect, onNotice, onError }) {
  const [data, setData] = useState(null)
  const [search, setSearch] = useState('')
  const [selected, setSelected] = useState(null)
  const [loading, setLoading] = useState(true)

  const load = useCallback(async () => {
    setLoading(true); setSelected(null)
    try {
      const path = section === 'opportunities' ? '/students/me/opportunities' : section === 'applications' ? '/students/me/applications' : section === 'internships' ? '/students/me/internships' : section === 'portfolio' || section === 'certifications' ? '/students/me/portfolio' : section === 'notifications' ? '/students/me/notifications' : '/students/me/profile'
      setData(await request(path, token))
    } catch (loadError) { onError(loadError.message) } finally { setLoading(false) }
  }, [onError, section, token])
  useEffect(() => { load() }, [load])

  async function act(path, options = {}) {
    try { await request(path, token, options); onNotice('Your career workspace is up to date'); await load() } catch (actionError) { onError(actionError.message) }
  }

  if (loading) return <div className="student-empty"><span className="student-spinner" /><h2>Loading your {section}</h2><p>Fetching your live career data.</p></div>
  if (section === 'opportunities') return <OpportunityView data={data} search={search} setSearch={setSearch} onOpen={async (id) => { try { setSelected(await request(`/students/me/opportunities/${id}`, token)) } catch (error) { onError(error.message) } }} selected={selected} onApply={(id) => act('/students/me/applications', { method: 'POST', body: JSON.stringify({ opportunityId: id }) })} onBack={() => setSelected(null)} />
  if (section === 'applications') return <ApplicationsView data={data} onOpen={async (id) => { try { setSelected(await request(`/students/me/applications/${id}`, token)) } catch (error) { onError(error.message) } }} selected={selected} onWithdraw={(id) => act(`/students/me/applications/${id}/withdraw`, { method: 'POST' })} onBack={() => setSelected(null)} onExplore={() => onSelect('opportunities')} />
  if (section === 'internships') return <InternshipsView items={data?.items || []} />
  if (section === 'portfolio' || section === 'certifications') return <PortfolioView data={data} section={section} onSave={act} onSelect={onSelect} />
  if (section === 'notifications') return <NotificationsView data={data} onRead={(id) => act(`/students/me/notifications/${id}/read`, { method: 'PATCH' })} onReadAll={() => act('/students/me/notifications/read-all', { method: 'PATCH' })} />
  return <SettingsView profile={data} onSave={(values) => act('/students/me/profile', { method: 'PATCH', body: JSON.stringify(values) })} />
}

function OpportunityView({ data, search, setSearch, onOpen, onApply, selected, onBack }) {
  if (selected) return <><Header kicker="OPPORTUNITY DETAILS" title={selected.role_title || selected.title} copy={`${selected.company?.name || selected.company_name} · ${label(selected.type)}`} action="Back to opportunities" onAction={onBack} /><article className="student-panel career-detail"><p>{selected.description}</p><div className="detail-grid"><span>Work mode<strong>{label(selected.work_mode)}</strong></span><span>Location<strong>{selected.location || 'Flexible'}</strong></span><span>Duration<strong>{selected.duration || 'Not specified'}</strong></span><span>Deadline<strong>{selected.application_deadline || 'Open'}</strong></span></div><PanelTitle kicker="WHY THIS MATCHES" title={selected.match ? `${selected.match.score}% ${label(selected.match.strength)} match` : 'Match is unavailable'} /><div className="match-list">{(selected.matchingSkills || []).map((skill) => <p key={skill.skill}>✓ {skill.skill} aligns with this role</p>)}{(selected.missingSkills || []).map((skill) => <p key={skill.skill} className="match-gap">△ Build {skill.skill} to strengthen your application</p>)}</div><button className="student-button" onClick={() => onApply(selected.id)}>Apply now <span>→</span></button></article></>
  const items = (data?.items || []).filter((item) => `${item.title} ${item.role_title} ${item.company_name}`.toLowerCase().includes(search.toLowerCase()))
  return <><Header kicker="CAREER MARKETPLACE" title="Opportunities" copy="Find the next place to learn, contribute, and prove what you can do." /><div className="student-toolbar"><input aria-label="Search opportunities" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search roles, companies, or skills" /><span>{data?.total || 0} live opportunities</span></div><div className="career-card-grid">{items.map((item) => <article className="student-panel opportunity-card" key={item.id}><p className="student-kicker">{label(item.type)}</p><h2>{item.role_title || item.title}</h2><strong>{item.company_name}</strong><p>{item.location || 'Flexible'} · {label(item.work_mode)}{item.duration ? ` · ${item.duration}` : ''}</p><small>Apply by {item.application_deadline || 'Open deadline'}</small><div><button className="student-link" onClick={() => onOpen(item.id)}>View details →</button><button className="student-button compact" onClick={() => onApply(item.id)}>Apply</button></div></article>)}{!items.length && <EmptyView title="No matching opportunities" copy="Try a different search or check back as new roles are published." />}</div></>
}

function ApplicationsView({ data, onOpen, selected, onWithdraw, onBack, onExplore }) { if (selected) return <><Header kicker="APPLICATION TRACKING" title={selected.opportunity_title} copy={`${selected.company_name} · ${label(selected.status)}`} action="Back to applications" onAction={onBack} /><article className="student-panel career-detail"><div className="status-pill">{label(selected.status)}</div><div className="timeline">{(selected.history || []).map((stage) => <div key={stage.id}><span>●</span><strong>{label(stage.to_status)}</strong><small>{new Date(stage.created_at).toLocaleDateString()}</small></div>)}</div>{selected.interviews?.map((interview) => <div className="interview-callout" key={interview.id}><strong>{interview.round_name || `Round ${interview.round_number}`} · {label(interview.mode)}</strong><p>{interview.scheduled_at ? new Date(interview.scheduled_at).toLocaleString() : 'To be scheduled'}</p>{interview.meeting_link && <a href={interview.meeting_link} target="_blank" rel="noreferrer">Open meeting link</a>}</div>)}{!['SELECTED', 'REJECTED', 'WITHDRAWN'].includes(selected.status) && <button className="student-link danger-link" onClick={() => onWithdraw(selected.id)}>Withdraw application</button>}</article></>; return <><Header kicker="YOUR MOMENTUM" title="Applications" copy="Keep every opportunity moving with a clear view of what happens next." /><div className="student-metric-grid application-metrics">{['APPLIED', 'UNDER_REVIEW', 'SHORTLISTED', 'INTERVIEW', 'SELECTED'].map((status) => <Metric key={status} label={label(status)} value={data?.counts?.find((item) => item.status === status)?.count || 0} note="live applications" tone="teal" />)}</div><div className="career-list">{(data?.items || []).map((item) => <button className="student-panel career-list-row" key={item.id} onClick={() => onOpen(item.id)}><span><strong>{item.opportunity_title}</strong><small>{item.company_name}</small></span><span className="status-pill">{label(item.status)}</span><span>→</span></button>)}</div>{!data?.items?.length && <EmptyView title="Your application story starts here" copy="Explore opportunities and apply when a role feels like the right next step." action="Explore opportunities" onAction={onExplore} />}</> }

function InternshipsView({ items }) { return <><Header kicker="EXPERIENCE WORKSPACE" title="Internships" copy="Turn your placement into visible progress and evidence." /><div className="career-card-grid">{items.map((item) => <article className="student-panel internship-card" key={item.id}><p className="student-kicker">{label(item.status)}</p><h2>{item.opportunity_title || 'Internship experience'}</h2><strong>{item.company_name || 'Industry partner'}</strong><div className="progress-track"><span style={{ width: `${item.progress}%` }} /></div><strong>{item.progress}% complete</strong><div className="timeline">{item.milestones.map((milestone) => <div key={milestone.id}><span>{milestone.completed_at ? '✓' : '○'}</span><strong>{milestone.title}</strong><small>{milestone.due_date || 'No due date'}</small></div>)}</div></article>)}{!items.length && <EmptyView title="No internships yet" copy="Selected opportunities will appear here with milestones, feedback, and verification." />}</div></> }

function PortfolioView({ data, section, onSave }) { return <><Header kicker="PROFESSIONAL SHOWCASE" title="Portfolio" copy="Build proof of your work that grows with every opportunity." action={section === 'portfolio' ? 'Add project' : 'Add certification'} onAction={() => { const title = section === 'portfolio' ? window.prompt('Project title') : window.prompt('Certification name'); if (title) onSave(section === 'portfolio' ? '/students/me/portfolio/projects' : '/students/me/portfolio/certifications', { method: 'POST', body: JSON.stringify(section === 'portfolio' ? { title } : { name: title, issuer: 'Independent credential' }) }) }} /><article className="portfolio-hero student-panel"><p className="student-kicker">{data?.profile?.course || 'STUDENT'} · CAREER PROOF</p><h2>{data?.profile?.first_name} {data?.profile?.last_name}</h2><p>{data?.profile?.bio || 'Add a professional summary to make your direction visible.'}</p></article><div className="career-card-grid">{(section === 'portfolio' ? data?.projects : data?.certifications)?.map((item) => <article className="student-panel opportunity-card" key={item.id}><p className="student-kicker">{section === 'portfolio' ? 'PROJECT' : 'CERTIFICATION'}</p><h2>{item.title || item.name}</h2><p>{item.description || item.issuer}</p>{item.project_url || item.credential_url ? <a href={item.project_url || item.credential_url} target="_blank" rel="noreferrer">View evidence →</a> : <small>Evidence link not added</small>}</article>)}</div></> }

function NotificationsView({ data, onRead, onReadAll }) { return <><Header kicker="SIGNALS" title="Notifications" copy="Stay close to the updates that shape your next move." action="Mark all read" onAction={onReadAll} /><div className="career-list">{(data?.items || []).map((item) => <button className={`student-panel career-list-row ${item.is_read ? '' : 'unread'}`} key={item.id} onClick={() => onRead(item.id)}><span><strong>{item.title}</strong><small>{item.body}</small></span><small>{new Date(item.created_at).toLocaleDateString()}</small></button>)}</div>{!data?.items?.length && <EmptyView title="All caught up" copy="Important application, interview, and internship updates will appear here." />}</> }

function SettingsView({ profile, onSave }) { return <><Header kicker="CONTROL CENTER" title="Settings" copy="Keep your career preferences and profile signals current." /><form className="student-panel profile-form" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); const values = Object.fromEntries(form.entries()); values.career_interests = String(values.career_interests || '').split(',').map((interest) => interest.trim()).filter(Boolean); onSave(values) }}><PanelTitle kicker="CAREER PREFERENCES" title="How should EduNexus guide you?" /><div className="student-form-grid"><Field name="first_name" label="First name" value={profile?.first_name} /><Field name="last_name" label="Last name" value={profile?.last_name} /><Field name="portfolio_url" label="Portfolio URL" value={profile?.portfolio_url} /><label className="wide-field">Career interests<input name="career_interests" defaultValue={(profile?.career_interests || []).join(', ')} placeholder="Backend, cloud, data" /></label></div><button className="student-button">Save preferences <span>→</span></button></form></> }